### ISSUE TITLE
14. Tensorflow使用子类API实现WideDeep模型 有写错的地方

### ISSUE THREAD

**Issue by Matrixmax** [peiss/ant-learn-tensorflow#1]
在搭建模型的部分中，进行concat的时候，应该是input_Wide和hidden3，这里写成了hidden2

**Comment by Matrixmax** [comment]
![image](https://user-images.githubusercontent.com/22517752/93748700-43d44700-fc2b-11ea-9232-457d3b7013e0.png)

**Comment by peiss** [comment]
已修复，谢谢。

关闭issue
